spring.application.name=TaskFlow
spring.datasource.url=JDBC:postgresql://localhost:5432/taskflow
spring.datasource.username=postgres
Spring.datasource.password=Sup3rm@n

spring.jpa.hibernate.ddl-auto=update